/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu.sr.blanco;

import controller.Professors_DAO;
import javax.swing.JOptionPane;

/**
 *
 * @author baruk
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        setUndecorated(true);
        initComponents();

        setSize(400, 300);
        setDefaultCloseOperation(Login.EXIT_ON_CLOSE);

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new Panel_gradiend.PanelGradient();
        passwordField1 = new textfield.PasswordField();
        textField1 = new textfield.TextField();
        btLogin = new javax.swing.JButton();
        titleBar1 = new javaswingdev.swing.titlebar.TitleBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(358, 500));
        setPreferredSize(new java.awt.Dimension(400, 700));

        panelGradient1.setBackground(new java.awt.Color(102, 102, 102));
        panelGradient1.setColorGradient(new java.awt.Color(0, 102, 204));
        panelGradient1.setPreferredSize(new java.awt.Dimension(100, 200));

        passwordField1.setBackground(new java.awt.Color(214, 217, 223));
        passwordField1.setLabelText("Mật Khẩu");
        panelGradient1.add(passwordField1);
        passwordField1.setBounds(100, 320, 200, 46);

        textField1.setBackground(new java.awt.Color(214, 217, 223));
        textField1.setLabelText("Tài Khoản");
        panelGradient1.add(textField1);
        textField1.setBounds(100, 270, 200, 46);

        btLogin.setBackground(new java.awt.Color(0, 153, 255));
        btLogin.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btLogin.setText("Đăng Nhập");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        panelGradient1.add(btLogin);
        btLogin.setBounds(130, 380, 130, 30);
        panelGradient1.add(titleBar1);
        titleBar1.setBounds(0, 0, 53, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("LOGIN");
        panelGradient1.add(jLabel1);
        jLabel1.setBounds(120, 150, 180, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        MenuOpcion menuFrame = new MenuOpcion();

        int user = 0;
    try {
        user = Integer.parseInt(textField1.getText().trim());
    } catch (NumberFormatException numberFormatException) {
        JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không đúng!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    String pass = new String(passwordField1.getPassword());
    Professors_DAO check = new Professors_DAO();
    boolean isAuthenticated = check.getInstance().checkLogin(user, pass);

    if (isAuthenticated) {
              JOptionPane.showMessageDialog(this, "Đăng Nhập Thành Công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

        menuFrame.setVisible(true);

        dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không đúng!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel jLabel1;
    private Panel_gradiend.PanelGradient panelGradient1;
    private textfield.PasswordField passwordField1;
    private textfield.TextField textField1;
    private javaswingdev.swing.titlebar.TitleBar titleBar1;
    // End of variables declaration//GEN-END:variables
}
